language: node_js
node_js:
  - 18

cache:
  directories:
    - node_modules

# Install Chrome for headless browser testing
addons:
  chrome: stable

before_install:
  - # Update npm to the latest version
  - npm i -g npm@latest

install:
  - npm ci

before_script:
  - # Start the headless Chrome browser
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - npm run test:ci

# Report coverage to Codecov
after_success:
  - npx codecov

# Deploy to Vercel if tests pass
deploy:
  provider: script
  script: npx vercel --prod --token $VERCEL_TOKEN
  skip_cleanup: true
  on:
    branch: main
