language: node_js
node_js:
  - 18

cache:
  directories:
    - node_modules

# Add Chrome for headless testing
addons:
  chrome: stable

before_install:
  # Upgrade npm to latest version
  - npm install -g npm@latest

install:
  # Prefer clean install; fallback to npm install
  - npm ci || npm install

before_script:
  # Start headless Chrome (for frontend test runners if needed)
  - google-chrome-stable --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  # Run tests and generate coverage
  - npm run test:ci

after_success:
  # Upload coverage report to Codecov
  - npx codecov

deploy:
  provider: script
  script: npx vercel --prod --token=$VERCEL_TOKEN
  skip_cleanup: true
  on:
    branch: main
